"""Constants for environment_loading module.

This module contains all constants related to environment variable loading,
configuration management, and retry settings.
"""

# Retry configuration constants
DEFAULT_WAIT_RANDOM_EXPONENTIAL_MIN = 55
DEFAULT_WAIT_RANDOM_EXPONENTIAL_MAX = 155
DEFAULT_STOP_AFTER_ATTEMPT_COUNT = 3

# Environment variable names for Azure OpenAI
ENV_AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT"
ENV_AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY"
ENV_AZURE_OPENAI_API_VERSION = "AZURE_OPENAI_API_VERSION"
ENV_AZURE_OPENAI_DEPLOYMENT_NAME = "AZURE_OPENAI_DEPLOYMENT_NAME"
ENV_AZURE_OPENAI_MODEL = "AZURE_OPENAI_MODEL"
ENV_UAIS_PROJECT_ID = "UAIS_PROJECT_ID"

# Environment variable names for embeddings
ENV_AZURE_OPENAI_EMBEDDINGS_ENDPOINT = "AZURE_OPENAI_EMBEDDINGS_ENDPOINT"
ENV_AZURE_OPENAI_EMBEDDINGS_API_KEY = "AZURE_OPENAI_EMBEDDINGS_API_KEY"
ENV_AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME = "AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME"
ENV_AZURE_OPENAI_EMBEDDING_MODEL_NAME = "AZURE_OPENAI_EMBEDDING_MODEL_NAME"

# Environment variable names for Hugging Face
ENV_HUGGING_FACE_EMBEDDING_MODEL_NAME = "HUGGING_FACE_EMBEDDING_MODEL_NAME"

# Environment variable names for Azure Document Intelligence
ENV_AZURE_APP_CLIENT_ID = "AZURE_APP_CLIENT_ID"
ENV_AZURE_APP_CLIENT_SECRET = "AZURE_APP_CLIENT_SECRET"
ENV_AZURE_APP_TENANT_ID = "AZURE_APP_TENANT_ID"
ENV_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT"

# PieceMeal Vector Store Writer Decorator Settings
ENV_PIECE_MEAL_WAIT_RANDOM_EXPONENTIAL_MIN = "PIECE_MEAL_VECTOR_STORE_WRITER_DECORATOR_SETTINGS_WAIT_RANDOM_EXPONENTIAL_MIN"
ENV_PIECE_MEAL_WAIT_RANDOM_EXPONENTIAL_MAX = "PIECE_MEAL_VECTOR_STORE_WRITER_DECORATOR_SETTINGS_WAIT_RANDOM_EXPONENTIAL_MAX"
ENV_PIECE_MEAL_STOP_AFTER_ATTEMPT_COUNT = "PIECE_MEAL_VECTOR_STORE_WRITER_DECORATOR_SETTINGS_STOP_AFTER_ATTEMPT_COUNT"

# LLM configuration constants
DEFAULT_TEMPERATURE = 0

# LLM Cache configuration
ENV_LLM_CACHE_TTL_SECONDS = "LLM_CACHE_TTL_SECONDS"
DEFAULT_LLM_CACHE_TTL_SECONDS = 3500  # HCP tokens expire at 3599s, use 3500s for safety buffer